require("nipunlakshank.config.globals")
require("nipunlakshank.config.options")
require("nipunlakshank.config.filetype")
require("nipunlakshank.config.autocmds")
require("nipunlakshank.config.usercmds")
require("nipunlakshank.config.keymaps")
