require("nipunlakshank.config.paths")
require("nipunlakshank.config.globals")
require("nipunlakshank.config.options")
require("nipunlakshank.config.lazy")
require("nipunlakshank.config.autocmds")
require("nipunlakshank.config.keymaps")
